# Site settings
title: Derek McBurney
description: I'm Derek. I make web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://derekmcburney.com" # the base hostname & protocol for your site
permalink: /blog/:title

# Build settings
markdown: kramdown
source: src
destination: _site

# Collections
collections:
  drupal-blog-posts:
    output: true
    permalink: /things/drupal-blog/:title/

defaults:
  - scope:
      path: ""
      type: drupal-blog-posts
    values:
      layout: drupal-blog-post
