# Site settings
title: Derek McBurney
email: d.mcburney@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://derekmcburney.com" # the base hostname & protocol for your site
twitter_username: derekmcb
github_username:  dmcb

# Build settings
markdown: kramdown
