# Site settings
baseurl: ""
url: "http://derekmcburney.com"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - package-lock.json
  - package.json

# Build settings
markdown: kramdown
source: src
destination: _site

# Collections
collections:
  drupal-blog-posts:
    output: true
    permalink: /things/drupal-blog/:title/

defaults:
  - scope:
      path: ""
      type: drupal-blog-posts
    values:
      layout: blog-post
