services:
  web:
    image: "node:20.12.2"
    command: 'bash -c "npm install && npm run dev"'
    ports:
      - "5173:5173"
    working_dir: "/svelte-sanity/"
    expose:
      - "5173"
    volumes:
      - "./web:/svelte-sanity/"
      - "node_modules:/svelte-sanity/node_modules"
      - "svelte_build_results:/svelte-sanity/.svelte-kit"
    restart: "on-failure"
    env_file:
      - "./web/.env"
    depends_on:
      - "cms"
  cms:
    image: "node:20.12.2"
    working_dir: "/svelte-sanity/"
    command: 'bash -c "yarn install && $$(yarn bin sanity) start --host=0.0.0.0"'
    ports:
      - "3333:3333"
    expose:
      - "3333"
    volumes:
      - "./sanity:/svelte-sanity/"
      - "sanity_node_modules:/svelte-sanity/node_modules"
    env_file:
      - "./sanity/.env"
volumes:
  svelte_build_results:
  node_modules:
  sanity_node_modules:
