services:
  web:
    image: "node:20.12.2"
    command: 'bash -c "npm install && npm run dev"'
    ports:
      - "5173:5173"
    working_dir: "/svelte-sanity/"
    expose:
      - "5173"
    volumes:
      - "./web:/svelte-sanity/"
    restart: "on-failure"
    env_file:
      - "./web/.env"
    depends_on:
      - "cms"
  cms:
    image: "node:20.12.2"
    working_dir: "/svelte-sanity/"
    command: 'bash -c "npm install && npm run dev"'
    ports:
      - "3333:3333"
    expose:
      - "3333"
    volumes:
      - "./sanity:/svelte-sanity/"
    env_file:
      - "./sanity/.env"
